
--k-- Modal supervisor keybinding, which can be used to temporarily disable ALL modal environments.
--khsupervisor_keys = {{"cmd", "shift", "ctrl"}, "Q"}
--k
--k-- Reload Hammerspoon configuration
--khsreload_keys = {{"cmd", "shift", "ctrl"}, "R"}
--k
--k-- Toggle help panel of this configuration.
--khshelp_keys = {{"alt", "shift"}, "/"}
--k
--k-- aria2 RPC host address
--khsaria2_host = "http://localhost:6800/jsonrpc"
--k-- aria2 RPC host secret
--khsaria2_secret = "token"
--k
--k----------------------------------------------------------------------------------------------------
--k-- Those keybindings below could be disabled by setting to {"", ""} or {{}, ""}
--k
--k-- Window hints keybinding: Focuse to any window you want
--khswhints_keys = {"alt", "tab"}
--k
--k-- appM environment keybinding: Application Launcher
--khsappM_keys = {"alt", "A"}
--k
--k-- clipshowM environment keybinding: System clipboard reader
--khsclipsM_keys = {"alt", "C"}
--k
--k-- Toggle the display of aria2 frontend
--khsaria2_keys = {"alt", "D"}
--k
--k-- Launch Hammerspoon Search
--khsearch_keys = {"alt", "G"}
--k
--k-- Read Hammerspoon and Spoons API manual in default browser
--khsman_keys = {"alt", "H"}
--k
--k-- countdownM environment keybinding: Visual countdown
--khscountdM_keys = {"alt", "I"}
--k
--k-- Lock computer's screen
--khslock_keys = {"alt", "L"}
--k
--k-- resizeM environment keybinding: Windows manipulation
--khsresizeM_keys = {"alt", "R"}
--k
--k-- cheatsheetM environment keybinding: Cheatsheet copycat
--khscheats_keys = {"alt", "S"}
--k
--k-- Show digital clock above all windows
--khsaclock_keys = {"alt", "T"}
--k
--k-- Type the URL and title of the frontmost web page open in Google Chrome or Safari.
--khstype_keys = {"alt", "V"}
--k
--k-- Toggle Hammerspoon console
--khsconsole_keys = {"alt", "Z"}
--k
